### ISSUE TITLE
Sketch file format documentation umbrella issue

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/SketchAPI#515]
Improve file format documentation so that developers writing integrations have a solid reference to the evolving Sketch file format. Such integrations could include Sketch file linters, or tools to generate Sketch files from other sources (i.e. React components).

The new documentation will attempt to satisfying the requirements of two fictional developer personas visiting the docs website:

- **Developer A** maintaining or debugging an existing integration across Sketch versions
- **Developer B** who is creating an integration from scratch against a specific (likely latest) version of Sketch

### Sub task list

- [x] Sample file documentation phase 1 (empty file sample) (#516)
- [x] Flesh out with additional sample files and plugins (https://github.com/BohemianCoding/SketchAPI/issues/525)
- [x] Spike worth/feasibility of generating a JSON Schema from xcdatamodel file (https://github.com/BohemianCoding/Sketch/issues/24735) _Edit: spike resulted in us not taking this route_
- [ ] MVP manually crafted file format JSON Schema
- [ ] Auto-generate docs from JSON Schema
- [ ] Document misc file format idiosyncrasies (item 3 below)
- [ ] Ability to switch versions on JSON Schema documentation (future phase?)
- [ ] Visualise diff between sample files across Sketch versions (future phase?)

Overall, there are three main areas of work:

### 1. Sample file documentation

Created to satisfy the needs of **Developer A** these sample files illustrate key areas of the Sketch file format. Including, but not limited to, sample files illustrating:

- An empty file
- Shapes
- Layers
- Symbols
- Etc...

Importantly we should visualise how each of these sample files changes between Sketch versions, so that partners have as much information as possible to troubleshoot problems or breaking changes.

#### Technical approach

1. For each sample type create a corresponding plugin that generates a Sketch file that illustrates it
1. Pretty print JSON from the Sketch file on the documentation website
1. For each new version of Sketch re-run the sample plugins and regenerate new pretty printed JSON
1. Provide a UI on the website for visualising the JSON diff between Sketch versions

#### Phase 1

An achievable first iteration of this feature would involve creating a sample plugin and page for just one or two simple feature areas (e.g. empty file). An exhaustive list of sample files, and the diff visualisation feature can be tackled subsequently.

### 2. File structure and JSON schema documentation

Created to satisfy the needs of **Developer B** this section of the website would document the following aspects:

- Main files and folders within the Sketch document archive
- For JSON files, document the schema fully with information about each field. At a minimum this documentation would include field names, data types and any other information exposed by the schema (e.g. required, enums etc.). Adding text descriptions to the schema is a nice to have.

The view would default to the latest version of Sketch, with a way to switch between versions of Sketch (note: the first iteration of this feature will just mean adding content for Sketch 55, or whatever the current version of Sketch is when we get around to this, we won't at this stage attempt to add documentation retrospectively for older versions).

#### Technical approach

A potential approach would be to add the field-level documentation as comments to the xcdatamodel file in the main Sketch repo. Tooling could be built to transform the XML into a [JSON Schema](https://json-schema.org/) which could serve the dual purpose of serving as a data source for the static website _and_ opening up the possibility of a Sketch document validation tool in future.

#### Phase 1

> TODO: Define an easily achievable MVP for this feature.

### 3. Other file format related documentation

Add documentation around edge cases and idiosyncratic aspects of the file format. Namely:

- The semantics of integer enums
- How Sketch handles file format migrations
- The additive behaviour of migrations between `compatibilityVersion` and `version`
- When and how breaking changes can occur
- Mapping between `version` and the publicly marketed Sketch version
- Coordinate concepts https://github.com/BohemianCoding/SketchAPI/issues/514

**Comment by christianklotz** [comment]
Closing, https://github.com/sketch-hq/sketch-file-format is out. Documentation from the schema is still the ambition but not possible until we have a website that makes it easier to do this.
