### ISSUE TITLE
Tests umbrella ☂️

### ISSUE THREAD

**Issue by bomberstudios** [sketch-hq/SketchAPI#732]
This is an umbrella issue for test-related issues

- [x] https://github.com/sketch-hq/SketchAPI/issues/722 fromSketchJSON is broken
- [x] https://github.com/sketch-hq/SketchAPI/issues/733 `SymboMaster.overrides` not working in Sketch 65
- [x] #734 Broken test: Library › should be able to get the list of symbols to be imported
- [x] #735 Broken tests in `CurvePoint`
- [x] #747 Reinstate expect calls in layer Text tests
- [x] #748 Reinstate expect calls in style Text tests

**Comment by jedrichards** [comment]
🎉
